[package]
name = "ndarray-rand"
version = "0.9.0"
edition = "2018"
authors = ["bluss"]
license = "MIT/Apache-2.0"

repository = "https://github.com/rust-ndarray/ndarray"
documentation = "https://docs.rs/ndarray-rand/"

description = "Constructors for randomized arrays. `rand` integration for `ndarray`."

keywords = ["multidimensional", "matrix", "rand", "ndarray"]

[dependencies]
rand = "0.6.0"
ndarray = { version = "0.12.0", path = ".." }

[package.metadata.release]
no-dev-version = true

